### ISSUE TITLE
Bootstrap CSS

### ISSUE THREAD

**Issue by AKaravas** [AgenturPottkinder/typo3_forum#188]
Can you please make Bootstrap CSS optional? Some people don't use Bootstrap and when they try to use the extension, it doesn't work at all.

**Comment by pstranghoener** [comment]
Hey, 

in my opinion its opional, you can choose that in the static templates if want bootstrap.

Best Regards Philipp

**Comment by AKaravas** [comment]
Well, as you can see here i didn't include bootstrap static template.

[http://image.prntscr.com/image/55a9ea10313d420d81a03a0aae4a9021.png](url)

Frotend

[http://image.prntscr.com/image/57c75d8cdafb4015bea7cb3763954bcf.png](url)

The css and js are removed because i am using foundation, and as a result, the extension doesnt work

**Comment by pstranghoener** [comment]
If i click on links i get an 404....

**Comment by AKaravas** [comment]
Now it works

**Comment by pstranghoener** [comment]
We can do that next year, the rest of the year is blocked for the migration script from mm_forum to typo3_forum. 

If you want to have it early you can make a pull request if you want. 

Best Regards Philipp

**Comment by Avalarion** [comment]
I am closing this issue. This is done with the 10x Release within the next few days.
