### ISSUE TITLE
post_count and topic_count on Forum

### ISSUE THREAD

**Issue by noli0me0tangere** [AgenturPottkinder/typo3_forum#245]
When a topic is deleted, the topic_count and post_count in table  tx_typo3forum_domain_model_forum_forum are not updated, resulting in wrong counting on forum startpage.

To solve, add in Classes\Domain\Factory\Forum\TopicFactory.php after Line 140:
`$this->forumRepository->update($forum);`

**Comment by mgrundkoetter** [comment]
I had to make the same fix because the lastTopic and lastPost fields are also wrong if the latest topic is deleted. This makes then crash the frontend with an extbase validation error due to unreachable object references. This is a major issue and the fix stated above solves it easily!

**Comment by Avalarion** [comment]
@sgrossberndt can you create a pull request for this?

**Comment by sgrossberndt** [comment]
https://github.com/AgenturPottkinder/typo3_forum/pull/341
