### ISSUE TITLE
[DOC][Question] Select a Subforum as entry point

### ISSUE THREAD

**Issue by mrwhy-orig** [AgenturPottkinder/typo3_forum#247]
We migrated a mm_forum to the typo3_forum. Until now it worked out all fine. But is it possible to select another entry point by now? At the moment we have "Forum" -> "SubForum1" -> X Other Subforums. The Plugin shows the Children of "Forum" which is just "SubForum1". I'd like to start with "SubForum1".

**Comment by Avalarion** [comment]
Hey @mrwhy-orig I guess that your ticket after nearly 3 years is not valid anymore so I am closing it. If you still have this problem and need help please write me here and I am going to reopen the issue.
