### ISSUE TITLE
Migration from mm_forum -> no Topic order.

### ISSUE THREAD

**Issue by mrwhy-orig** [AgenturPottkinder/typo3_forum#248]
The script is missing the last_post_crdate update. This leads to an unordered topic list, because the show action of the ForumController uses findForIndex function from the TopicRepository which ordering is last_post_crdate DESC.

**Comment by pkerling** [comment]
`UPDATE tx_typo3forum_domain_model_forum_topic SET last_post_crdate = (SELECT crdate FROM tx_typo3forum_domain_model_forum_post WHERE uid = last_post)` should fix it
