### ISSUE TITLE
PDF Attachments are useless at download

### ISSUE THREAD

**Issue by mrwhy-orig** [AgenturPottkinder/typo3_forum#252]
PDF Attachments are broken at the time of downloading. If get the attachment via ftp and add the file identifier (.pdf) the PDF is working. But if I download them from the Forum they are broken.

**Comment by sigma67** [comment]
Are you using the latest version? The issue should be fixed since 1f7b0fa750c421f3a4e6ec21e5d5bf7504980c1b

**Comment by mrwhy-orig** [comment]
Yes, i used the latest version. Anyway i applied the patch in the code now and it seems to work.

**Comment by mrwhy-orig** [comment]
Nope... not working. Still problems with PDF. Other files are working fine.

**Comment by sgrossberndt** [comment]
Works for me with `v1.2.0` 2ac0b3c

**Comment by Avalarion** [comment]
Tested this as well and after more than 2 years I am going to close this issue. If you @mrwhy-orig still have this issue please reopen it.
