### ISSUE TITLE
checkAccess in Forum has no default return value

### ISSUE THREAD

**Issue by mgrundkoetter** [AgenturPottkinder/typo3_forum#254]
I have a constellation of ACL/Forum where the `checkAccess` method in `Classes/Domain/Model/Forum/Forum.php` finally returns null (because no return statement is reached). This leads to being able to do everything in frontend if you are anonymous user. Simple fix for this is to just add
`return false;` as last line in the mentioned method. This translates to: you are allowed to do nothing by default except you have been given access.

**Comment by Avalarion** [comment]
Resolved so closing this issue: https://github.com/AgenturPottkinder/typo3_forum/blob/master/Classes/Domain/Model/Forum/Forum.php#L469
