### ISSUE TITLE
The action "reportShow" (controller "Moderation") is not allowed by this plugin

### ISSUE THREAD

**Issue by Sa-Lat** [AgenturPottkinder/typo3_forum#259]
Hi there, 
in template files 
`typo3conf/ext/typo3_forum/Resources/Private/Templates/Standard/Moderation/IndexReport.html` 
(both standard and bootstrap)

there's a f:link.action to action 'reportShow' but this one does not exist. 

`<f:link.action action="reportShow" arguments="{report: report}">{report.topic.subject}</f:link.action>`

Maybe it should be a link to action 'editReport'?

Cheers

**Comment by Avalarion** [comment]
This is fixed in the template of 10x.
