### ISSUE TITLE
Protected forum access is slow with many entries as indexes are missing

### ISSUE THREAD

**Issue by velletti** [AgenturPottkinder/typo3_forum#315]
### Solution:

Add this 2 indexes speeds up a lot all queries that checks if the user has access to forum / topic
 
```
CREATE TABLE tx_typo3forum_domain_model_forum_access (
  KEY forum (forum,operation(15)),
  KEY group (forum,operation(15),affected_group)

}
```

for us (300.000 forums entries, TYPO3 LTS 8 , 20 different Usergroups, 8 languages) f.e. "latest Forums entries" it was more than 2 times faster

**Comment by velletti** [comment]
If one uses the forum in different languages and has many forum sections and many Topics, the Forum OverView page has the same Problem:

very slow .. 

## solution: 

`CREATE TABLE tx_mmforum_domain_model_forum_forum (
  KEY lang (sys_language_uid),
  KEY forumlng (forum,sys_language_uid),
}`

**Comment by sgrossberndt** [comment]
Hi! How did you setup your forum with multilanguage-support? I added a pull request removing the workspaces and to me seemingly incomplete multilanguage-setup: https://github.com/mittwald/typo3_forum/pull/285/commits/e4baad23d9ca23f16fc756bf89d3c87b9b726291

Do you have forums which are available in some languages only?

**Comment by kpurrmann** [comment]
@velletti Feel free to add an PR with your changes.

**Comment by velletti** [comment]
@kpurrmann  : Which branch should i checkout ? Master, develop , any other ?

**Comment by velletti** [comment]
@sgrossberndt : i am using a Private fork of this forum that we started i think 4 Years ago. As during that time the development for typo3_forum  was not going on, we  did all this in our fork.

**Comment by kpurrmann** [comment]
@velletti use master branch, thx

**Comment by Avalarion** [comment]
Closed in the 10x Branch.
