### ISSUE TITLE
[FEATURE] allow debugging via <f:debug>

### ISSUE THREAD

**Issue by ineswillenbrock** [AgenturPottkinder/typo3_forum#345]
I've got a possible feature request or a bug:

TYPO3 9.5.13
typo_forum 1.2.0

Would it be possible to allow debugging and extending Templates via <f:debug>{_all}</f:debug>?
Everytime something with users is in that array, the following error occurs:

```
Oops, an error occurred!
Cannot access private property Mittwald\Typo3Forum\Domain\Model\User\FrontendUser::$settings
```

`plugin.tx_typo3forum.settings.debug = 1` is allready set

Thanks, Ines

**Comment by sgrossberndt** [comment]
This will definitely not part of official templates. If you need to debug add that to templates yourself (best in overridden templates by path).

**Comment by ineswillenbrock** [comment]
Sure, I did try adding  <f:debug>{_all}</f:debug> and got the mentioned error.
That is what I'm asking, if it will be possible to add  the debugging code and not get errors :)

No, the default template should really not use <f:debug>, that's ok.

**Comment by Avalarion** [comment]
Works in 10x Branch so should be fixed =).
