### ISSUE TITLE
error in Database analyzer

### ISSUE THREAD

**Issue by manuelLink** [AgenturPottkinder/typo3_forum#349]
the Database analyzer shows three Database fields as incorrect:

ALTER TABLE \`tx_typo3forum_domain_model_format_textparser\` CHANGE \`type\` \`type\` VARCHAR(64) DEFAULT 'Mittwald\\Typo3Forum\\Domain\\Model\\Format\\BBCode' NOT NULL 

Current value: type VARCHAR(64) DEFAULT 'Mittwald\Typo3Forum\Domain\Model\Format\BBCode' NOT NULL COLLATE utf8_general_ci

ALTER TABLE \`tx_typo3forum_domain_model_moderation_report\` CHANGE \`type\` \`type\` VARCHAR(64) DEFAULT 'Mittwald\\Typo3Forum\\Domain\\Model\\Moderation\\UserReport' NOT NULL 
Current value: type VARCHAR(64) DEFAULT 'Mittwald\Typo3Forum\Domain\Model\Moderation\UserReport' NOT NULL COLLATE utf8_general_ci

ALTER TABLE \`tx_typo3forum_domain_model_user_notification\` CHANGE \`type\` \`type\` VARCHAR(64) DEFAULT 'Mittwald\\Typo3Forum\\Domain\\Model\\Forum\\Post' NOT NULL 
Current value: type VARCHAR(64) DEFAULT 'Mittwald\Typo3Forum\Domain\Model\Forum\Post' NOT NULL COLLATE utf8_general_ci

this seems to be because of the escaping of the "\\", since changing it to single backslashes removes the messages (but obviously would lead to wrong database fields)

not sure if this can be fixed within the typo3_forum-extension other than actualy changing the default value of the fields...

**Comment by Avalarion** [comment]
This seams to be fixed and is not showing up on a fresh 10x Version ( just tested ).
