### ISSUE TITLE
[FEATURE] Allowing ACLs via TypoScript

### ISSUE THREAD

**Issue by neufeind** [AgenturPottkinder/typo3_forum#35]
It would be great to be able to apply ACLs via TypoScript.

But what could that look like? Do we want to use special conditons? I think that would be doable through user-functions. Pseudo-code:

plugin.tx_mmforum.currentForum.acls {
read = everyone
}
// only allow posting starting from second level
[user_func(mmforum_forumlevel) > 1]
plugin.tx_mmforum.currentForum.acls {
writePost = everyone
}
[user_func(mmforum_rootline) contains 234] && [user_func(mmforum_forumlevel) > 1]
plugin.tx_mmforum.currentForum.acls {
moderate = group
moderatate.groupUid = 5
}

Would that be a viable solution?

**Comment by alat54** [comment]
Will be great :)

**Comment by Avalarion** [comment]
We are not going to do this.
