### ISSUE TITLE
Creating Topics without user session

### ISSUE THREAD

**Issue by z35Wegner** [AgenturPottkinder/typo3_forum#350]
Greetings,

it is possible to create or answer a topic without a valid user session.
To Setup, you have to have a valid account:
Log into your forum, navigate to a topic of your choice or create a new one.
Copy the link to the new post/topic link.
Paste that link into another browser or send it to someone else.
You can now create a new post/topic without any author informations. 

Our quick & dirty fix was to edit the fluid template and add a ```<f:security.ifAuthenticated>```-tag around the form.

This will remove the possibility to just send the form in another browser, but does not prevent your logged in user to delete his fe_user cookie and post.

**Comment by derhansen** [comment]
Since this is a security issue, please remember to always send your findings to security@typo3.org  first, so the TYPO3 Security Team can handle the issue together with the extension author.

**Comment by derhansen** [comment]
https://typo3.org/security/advisory/typo3-ext-sa-2020-010

**Comment by Avalarion** [comment]
Fixed with VErsion 1.2.1
