### ISSUE TITLE
Extension is searching a new maintainer 

### ISSUE THREAD

**Issue by pstranghoener** [AgenturPottkinder/typo3_forum#351]
More Information can be found here:  [https://www.mittwald.de/blog/cms/typo3-cms/typo3-forum-extension-neuer-maintainer](url)

**Comment by ineswillenbrock** [comment]
Hi, 
I'm willing to help (again, after years of being silent)  - but not to be the maintainer as I think it's a bit to big for me.
regards - Ines

**Comment by pstranghoener** [comment]
Hi Ines, thanks for your willing to help. 
But we are really searching for someone or a company who is taking the role of the maintainer. 

Best Regards Philipp

**Comment by Avalarion** [comment]
This issue is solved: https://www.mittwald.de/blog/cms/typo3-cms/maintainer-fuer-typo3-forum-pottkinder
