### ISSUE TITLE
[FEATURE] - As not all will install an external Search like Solr forum should have a Search plugin

### ISSUE THREAD

**Issue by velletti** [AgenturPottkinder/typo3_forum#50]
I will include such a plugin with following Main Features in the next weeks :

respect actuall sys_language_uid (for multi language forums)
search in Text and title 

an a Advanced Search with :

search filters:
- by Autor (by username) 
- only in specific forum (by Category)
- created after / before date
- contains specific TAG

additional options :
- is marked as solved
- search only in first Posts (request)
- i wrote this Post (quick option to fill by Author with the own username) 

If time i also create an indexer like in mm_forum 1.9.2 to have a Wordlist for a AJAX suggest list.

**Comment by pstranghoener** [comment]
Could this issue be closed?

**Comment by Avalarion** [comment]
Closing this issue now. We are not ging to include a own search to the forum. If you need this please create a pull request with SOLR or KeSearch configuration. If there is time this could be done for a next release if no one wants to do this and will be done in a new issue.
