### ISSUE TITLE
Approval workflow

### ISSUE THREAD

**Issue by jolantadworczyk** [AgenturPottkinder/typo3_forum#93]
Hello!

Is it in works to extend the extenstion about the feature of an approval workflow?
A user answers to a topic, and a moderator hast to check (release) it first.

Jolanta

**Comment by pstranghoener** [comment]
Hello, 

there are now plans to a workflow like this, but feel free to program it and make a pull request for that. 

Best Regards Philipp

**Comment by Avalarion** [comment]
Closing this issue. Please create a new one if this is still valid.
